### ISSUE TITLE
unpackerr error log with : in UN_SONARR_0_URL/UN_RADARR_0_URL

### ISSUE THREAD

**Issue by ErikTMA** [hotio/docker-unpackerr#1]
With the following docker-compose, I get these errors in the unpackerr.log file:
2020/08/24 20:00:04 [ERROR] Sonarr ("http://sonarr:8989"): c.Req(queue): http.NewRequest(path): parse "\"http://sonarr:8989\"/api/queue": first path segment in URL cannot contain colon
2020/08/24 20:00:04 [ERROR] Radarr ("http://radarr:7878"): c.Req(queue): http.NewRequest(path): parse "\"http://radarr:7878\"/api/queue": first path segment in URL cannot contain colon

docker-compose:
unpackerr:
    image: hotio/unpackerr
    container_name: unpackerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - UMASK_SET=022 #optional
      - ARGS=""
      - DEBUG="no"
      - UN_SONARR_0_URL="http://sonarr:8989"
      - UN_SONARR_0_API_KEY="--omitted--"
      - UN_RADARR_0_URL="http://radarr:7878"
      - UN_RADARR_0_API_KEY="--omitted--"
    volumes:
      - ./containers/unpackerr/config:/config
      - ./downloads:/downloads
    links:
      - "radarr:radarr"
      - "sonarr:sonarr"
    restart: unless-stopped

I have not tested if unpackerr works anyway.

**Comment by ErikTMA** [comment]
Okay, nevermind. The error message is misleading, and I should actually just remove the "" around the urls.

**Comment by hotio** [comment]
That's not a valid compose file, please fix your compose before continuing

**Comment by ErikTMA** [comment]
If you refer to the "#optional" string, it is actually valid. I have passwords with that written in my transmission container, and that works like a peach. Believe as long as there is a space in front of it, the yaml compiler understands it.

**Comment by ErikTMA** [comment]
But thanks for the incredibly swift response.

**Comment by hotio** [comment]
I meant that UMASK_SET is a lsio thing and won't work with my images, I use UMASK

**Comment by ErikTMA** [comment]
Ahh okay, thanks mate :)

**Comment by fiqabumm** [comment]
[_unpackerr_logs (1).txt](https://github.com/hotio/unpackerr/files/8057300/_unpackerr_logs.1.txt)
not sure what i am doing wrong it does find the sonarr and radarr server but cannot find any files and i am getting error but not sure how to get rid of them
